// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/styles.css.ts";
import * as $$0 from "./islands/AddToCartActions.tsx";
import * as $$1 from "./islands/AddToCartButton.tsx";
import * as $$2 from "./islands/BackToTopButton.tsx";
import * as $$3 from "./islands/BuyTogether.tsx";
import * as $$4 from "./islands/BuyWarning.tsx";
import * as $$5 from "./islands/CloseButton.tsx";
import * as $$6 from "./islands/Debug.tsx";
import * as $$7 from "./islands/HeaderButton.tsx";
import * as $$8 from "./islands/HeaderModals.tsx";
import * as $$9 from "./islands/HeaderSearchbar.tsx";
import * as $$10 from "./islands/HomeSearch.tsx";
import * as $$11 from "./islands/Newsletter.tsx";
import * as $$12 from "./islands/NewsletterModal.tsx";
import * as $$13 from "./islands/OutOfStock.tsx";
import * as $$14 from "./islands/ProductDetails.tsx";
import * as $$15 from "./islands/ProductDetailsImages.tsx";
import * as $$16 from "./islands/ProductGallery.tsx";
import * as $$17 from "./islands/ProductImageZoom.tsx";
import * as $$18 from "./islands/ProductReviews.tsx";
import * as $$19 from "./islands/QuickReview.tsx";
import * as $$20 from "./islands/SearchControls.tsx";
import * as $$21 from "./islands/SearchResultsGridChoice.tsx";
import * as $$22 from "./islands/ShareButton.tsx";
import * as $$23 from "./islands/ShippingSimulation.tsx";
import * as $$24 from "./islands/SliderJS.tsx";
import * as $$25 from "./islands/Sort.tsx";
import * as $$26 from "./islands/TopBar.tsx";
import * as $$27 from "./islands/WishlistButton.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/styles.css.ts": $1,
  },
  islands: {
    "./islands/AddToCartActions.tsx": $$0,
    "./islands/AddToCartButton.tsx": $$1,
    "./islands/BackToTopButton.tsx": $$2,
    "./islands/BuyTogether.tsx": $$3,
    "./islands/BuyWarning.tsx": $$4,
    "./islands/CloseButton.tsx": $$5,
    "./islands/Debug.tsx": $$6,
    "./islands/HeaderButton.tsx": $$7,
    "./islands/HeaderModals.tsx": $$8,
    "./islands/HeaderSearchbar.tsx": $$9,
    "./islands/HomeSearch.tsx": $$10,
    "./islands/Newsletter.tsx": $$11,
    "./islands/NewsletterModal.tsx": $$12,
    "./islands/OutOfStock.tsx": $$13,
    "./islands/ProductDetails.tsx": $$14,
    "./islands/ProductDetailsImages.tsx": $$15,
    "./islands/ProductGallery.tsx": $$16,
    "./islands/ProductImageZoom.tsx": $$17,
    "./islands/ProductReviews.tsx": $$18,
    "./islands/QuickReview.tsx": $$19,
    "./islands/SearchControls.tsx": $$20,
    "./islands/SearchResultsGridChoice.tsx": $$21,
    "./islands/ShareButton.tsx": $$22,
    "./islands/ShippingSimulation.tsx": $$23,
    "./islands/SliderJS.tsx": $$24,
    "./islands/Sort.tsx": $$25,
    "./islands/TopBar.tsx": $$26,
    "./islands/WishlistButton.tsx": $$27,
  },
  baseUrl: import.meta.url,
};

export default manifest;
