// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/blog/countView.ts";
import * as $$$$$$$$$1 from "./actions/blog/submitNewsletter.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$2 from "./apps/decohub.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$0 from "./loaders/posts/posts.ts";
import * as $$$1 from "./loaders/posts/views.ts";
import * as $$$$$$0 from "./sections/Blog/BlogBreadcrumb.tsx";
import * as $$$$$$1 from "./sections/Blog/BlogPostDetail.tsx";
import * as $$$$$$2 from "./sections/Blog/BlogPosts.tsx";
import * as $$$$$$3 from "./sections/Blog/BlogSidebar.tsx";
import * as $$$$$$4 from "./sections/Blog/Hero.tsx";
import * as $$$$$$5 from "./sections/Category/CategoriesCarroussel.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryBreadcrumb.tsx";
import * as $$$$$$8 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$9 from "./sections/Category/CategoryText.tsx";
import * as $$$$$$10 from "./sections/Container.tsx";
import * as $$$$$$11 from "./sections/Content/Benefits.tsx";
import * as $$$$$$12 from "./sections/Content/CopyRight.tsx";
import * as $$$$$$13 from "./sections/Content/Faq.tsx";
import * as $$$$$$14 from "./sections/Content/InfoCard.tsx";
import * as $$$$$$15 from "./sections/Content/InfoCardSeo.tsx";
import * as $$$$$$16 from "./sections/Content/Logos.tsx";
import * as $$$$$$17 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$18 from "./sections/DesignSystem/DesignSystem.tsx";
import * as $$$$$$19 from "./sections/Footer/Footer.tsx";
import * as $$$$$$20 from "./sections/Header/Buttons.tsx";
import * as $$$$$$21 from "./sections/Header/HeaderLayout.tsx";
import * as $$$$$$22 from "./sections/Header/HeaderNavMenu.tsx";
import * as $$$$$$23 from "./sections/Header/TopNavBar.tsx";
import * as $$$$$$24 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$25 from "./sections/Images/Carousel.tsx";
import * as $$$$$$26 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$27 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$28 from "./sections/Institutional/AccordionsContent.tsx";
import * as $$$$$$29 from "./sections/Institutional/AsideMenu.tsx";
import * as $$$$$$30 from "./sections/Institutional/CardsContent.tsx";
import * as $$$$$$31 from "./sections/Institutional/ContactForm.tsx";
import * as $$$$$$32 from "./sections/Institutional/InstitutionalPage.tsx";
import * as $$$$$$33 from "./sections/Institutional/StoreLocator.tsx";
import * as $$$$$$34 from "./sections/Institutional/TextContent.tsx";
import * as $$$$$$35 from "./sections/Integrations/JivoChat.tsx";
import * as $$$$$$36 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$37 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$38 from "./sections/Miscellaneous/BannerMarcas.tsx";
import * as $$$$$$39 from "./sections/Miscellaneous/BlogPosts.tsx";
import * as $$$$$$40 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$41 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$42 from "./sections/Miscellaneous/NotFound.tsx";
import * as $$$$$$43 from "./sections/Miscellaneous/ProxyIframe.tsx";
import * as $$$$$$44 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$45 from "./sections/Newsletter/NewsletterModal.tsx";
import * as $$$$$$46 from "./sections/Product/HomeSearch.tsx";
import * as $$$$$$47 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$48 from "./sections/Product/ProductReview.tsx";
import * as $$$$$$49 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$50 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$51 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$52 from "./sections/Seo/CustomBlogSEO.tsx";
import * as $$$$$$53 from "./sections/Seo/CustomProductSEO.tsx";
import * as $$$$$$54 from "./sections/Seo/SeoBaseCustomV2.tsx";
import * as $$$$$$55 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$56 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$57 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/posts/posts.ts": $$$0,
    "site/loaders/posts/views.ts": $$$1,
  },
  "sections": {
    "site/sections/Blog/BlogBreadcrumb.tsx": $$$$$$0,
    "site/sections/Blog/BlogPostDetail.tsx": $$$$$$1,
    "site/sections/Blog/BlogPosts.tsx": $$$$$$2,
    "site/sections/Blog/BlogSidebar.tsx": $$$$$$3,
    "site/sections/Blog/Hero.tsx": $$$$$$4,
    "site/sections/Category/CategoriesCarroussel.tsx": $$$$$$5,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$6,
    "site/sections/Category/CategoryBreadcrumb.tsx": $$$$$$7,
    "site/sections/Category/CategoryList.tsx": $$$$$$8,
    "site/sections/Category/CategoryText.tsx": $$$$$$9,
    "site/sections/Container.tsx": $$$$$$10,
    "site/sections/Content/Benefits.tsx": $$$$$$11,
    "site/sections/Content/CopyRight.tsx": $$$$$$12,
    "site/sections/Content/Faq.tsx": $$$$$$13,
    "site/sections/Content/InfoCard.tsx": $$$$$$14,
    "site/sections/Content/InfoCardSeo.tsx": $$$$$$15,
    "site/sections/Content/Logos.tsx": $$$$$$16,
    "site/sections/Content/Testimonials.tsx": $$$$$$17,
    "site/sections/DesignSystem/DesignSystem.tsx": $$$$$$18,
    "site/sections/Footer/Footer.tsx": $$$$$$19,
    "site/sections/Header/Buttons.tsx": $$$$$$20,
    "site/sections/Header/HeaderLayout.tsx": $$$$$$21,
    "site/sections/Header/HeaderNavMenu.tsx": $$$$$$22,
    "site/sections/Header/TopNavBar.tsx": $$$$$$23,
    "site/sections/Images/BannerGrid.tsx": $$$$$$24,
    "site/sections/Images/Carousel.tsx": $$$$$$25,
    "site/sections/Images/ImageGallery.tsx": $$$$$$26,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$27,
    "site/sections/Institutional/AccordionsContent.tsx": $$$$$$28,
    "site/sections/Institutional/AsideMenu.tsx": $$$$$$29,
    "site/sections/Institutional/CardsContent.tsx": $$$$$$30,
    "site/sections/Institutional/ContactForm.tsx": $$$$$$31,
    "site/sections/Institutional/InstitutionalPage.tsx": $$$$$$32,
    "site/sections/Institutional/StoreLocator.tsx": $$$$$$33,
    "site/sections/Institutional/TextContent.tsx": $$$$$$34,
    "site/sections/Integrations/JivoChat.tsx": $$$$$$35,
    "site/sections/Links/LinkTree.tsx": $$$$$$36,
    "site/sections/Links/Shortcuts.tsx": $$$$$$37,
    "site/sections/Miscellaneous/BannerMarcas.tsx": $$$$$$38,
    "site/sections/Miscellaneous/BlogPosts.tsx": $$$$$$39,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$40,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$41,
    "site/sections/Miscellaneous/NotFound.tsx": $$$$$$42,
    "site/sections/Miscellaneous/ProxyIframe.tsx": $$$$$$43,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$44,
    "site/sections/Newsletter/NewsletterModal.tsx": $$$$$$45,
    "site/sections/Product/HomeSearch.tsx": $$$$$$46,
    "site/sections/Product/ProductDetails.tsx": $$$$$$47,
    "site/sections/Product/ProductReview.tsx": $$$$$$48,
    "site/sections/Product/ProductShelf.tsx": $$$$$$49,
    "site/sections/Product/SearchResult.tsx": $$$$$$50,
    "site/sections/Product/Wishlist.tsx": $$$$$$51,
    "site/sections/Seo/CustomBlogSEO.tsx": $$$$$$52,
    "site/sections/Seo/CustomProductSEO.tsx": $$$$$$53,
    "site/sections/Seo/SeoBaseCustomV2.tsx": $$$$$$54,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$55,
    "site/sections/Social/WhatsApp.tsx": $$$$$$56,
    "site/sections/Theme/Theme.tsx": $$$$$$57,
  },
  "actions": {
    "site/actions/blog/countView.ts": $$$$$$$$$0,
    "site/actions/blog/submitNewsletter.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/records.ts": $$$$$$$$$$$1,
    "site/apps/decohub.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
