// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./loaders/tags.ts";
import * as $$$$$$1 from "./loaders/getCategoryTree.ts";
import * as $$$$$$2 from "./loaders/collections/list.ts";

const manifest = {
  name: "app-tags",
  baseUrl: import.meta.url,
  "loaders": {
    "site/app-tags/loaders/tags.ts": $$$$$$0,
    "site/app-tags/loaders/getCategoryTree.ts": $$$$$$1,
    "site/app-tags/loaders/collections/list.ts": $$$$$$2,
  },
};

export type Manifest = typeof manifest;

export default manifest;
